import type { LucideIcon } from "lucide-react";
import {
  Apple,
  Baby,
  Bed,
  Bike,
  Bone,
  Book,
  BookOpen,
  Boxes,
  Briefcase,
  Building,
  Building2,
  Car,
  Cat,
  Circle,
  Clock,
  Code,
  Cog,
  Dog,
  Download,
  Dumbbell,
  Droplet,
  Factory,
  FileText,
  Footprints,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Hammer,
  HeartHandshake,
  Home,
  Image,
  Key,
  KeyRound,
  Lamp,
  Laptop,
  LayoutGrid,
  Map,
  Monitor,
  Package,
  Palette,
  PawPrint,
  Printer,
  Puzzle,
  Search,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Store,
  Tablet,
  TrendingUp,
  Trophy,
  Truck,
  Utensils,
  Users,
  Watch,
  Wrench,
  Zap,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  cart: ShoppingCart,
  smartphone: Smartphone,
  building: Building,
  car: Car,
  briefcase: Briefcase,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  home: Home,
  heart: Heart,
  utensils: Utensils,
  gamepad: Gamepad2,
  paw: PawPrint,
  book: Book,
  factory: Factory,
  download: Download,
  users: Users,
  package: Package,
  microwave: LayoutGrid,
  bike: Bike,
  tablet: Tablet,
  headphones: LayoutGrid,
  watch: Watch,
  laptop: Laptop,
  "building-2": Building2,
  bed: Bed,
  store: Store,
  map: Map,
  key: Key,
  truck: Truck,
  wrench: Wrench,
  zap: Zap,
  clock: Clock,
  hammer: Hammer,
  footprints: Footprints,
  bag: ShoppingBag,
  baby: Baby,
  sofa: Sofa,
  lamp: Lamp,
  sparkles: Sparkles,
  palette: Palette,
  droplet: Droplet,
  dumbbell: Dumbbell,
  "chef-hat": Utensils,
  apple: Apple,
  "trending-up": TrendingUp,
  "gamepad-2": Gamepad2,
  monitor: Monitor,
  puzzle: Puzzle,
  trophy: Trophy,
  dog: Dog,
  cat: Cat,
  bone: Bone,
  "heart-handshake": HeartHandshake,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  "key-round": KeyRound,
  cog: Cog,
  printer: Printer,
  boxes: Boxes,
  image: Image,
  code: Code,
  "file-text": FileText,
  calendar: LayoutGrid,
  search: Search,
  gift: Gift,
};

/** Maps seed icon keys to Lucide components (Facebook Marketplace–style rail). */
export function CategoryIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = MAP[name] ?? Circle;
  return <Icon className={className} aria-hidden />;
}
